Possible new features & FIxes - Needs checking
TheDeveloperDen/DevDenBot pull request #180
Opened 2021-08-19 11:25 UTC by UntouchedOdin0

Possible fix for double bump and a possible new feature? need someone to check it over

2021-08-19 11:33 UTC, knightzmc requested changes

2021-08-19 11:33 UTC, knightzmc commented on src/main/kotlin/net/developerden/devdenbot/commands/info/StackOverflowCommand.kt
> +        val response = URL(question.replace("https://api.stackexchange.com/2.3/search/advanced?order=desc&sort=activity&q=$question",
Does this work?

2021-08-19 11:33 UTC, knightzmc commented on src/main/kotlin/net/developerden/devdenbot/commands/info/StackOverflowCommand.kt
> +        reply("Searching stackoverflow for $question")
You need to `.await()` the `reply` calls

2021-08-19 11:33 UTC, knightzmc commented on src/main/kotlin/net/developerden/devdenbot/listener/BumpNotificationListener.kt
> +        return
This is unnecessary, it won't fix anything

2021-09-10 15:59 UTC, UntouchedOdin0 reviewed
I thought this would be cool, idk how to remove the other things sorry

2021-09-11 13:24 UTC, closed without merging